require('keys.alias')
local set = vim.keymap.set

Nm("<C-A-r>", ":NvimTreeRefresh<CR>")
Nm("<C-e>", ":NvimTreeToggle<CR>")
Nm("<C-g>", ":LazyGit<CR>")

-- lsp keymaps
set("n", "gd", vim.lsp.buf.definition)
set("n", "K", vim.lsp.buf.hover)
set("n", "<leader>vws", vim.lsp.buf.workspace_symbol)
set("n", "<leader>vd", vim.diagnostic.open_float)
set("n", "[d", vim.diagnostic.goto_next)
set("n", "]d", vim.diagnostic.goto_prev)
set("n", "<leader>vca", vim.lsp.buf.code_action)
set("n", "<leader>vrr", vim.lsp.buf.references)
set("n", "<f2>", vim.lsp.buf.rename)

-- cmake keymaps
Nm("<f7>", ":CMakeBuild<CR>")
Nm("<f5>", ":CMakeRun<CR>")
Nm("<f6>", ":CMakeSelectLaunchTarget<CR>")
--
-- -- nvim-tree
-- local nvim_tree_api = require('nvim-tree.api')
-- local function opts(desc)
--     return { desc = "nvim-tree: " .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
-- end
--
-- set("n", "<C-]>",          nvim_tree_api.tree.change_root_to_node,       opts("CD"))
-- set("n", "<C-e>",          nvim_tree_api.node.open.replace_tree_buffer,  opts("Open: In Place"))
-- set("n", "<C-k>",          nvim_tree_api.node.show_info_popup,           opts("Info"))
-- set("n", "<C-r>",          nvim_tree_api.fs.rename_sub,                  opts("Rename: Omit Filename"))
-- set("n", "<C-t>",          nvim_tree_api.node.open.tab,                  opts("Open: New Tab"))
-- set("n", "<C-v>",          nvim_tree_api.node.open.vertical,             opts("Open: Vertical Split"))
-- set("n", "<C-x>",          nvim_tree_api.node.open.horizontal,           opts("Open: Horizontal Split"))
-- set("n", "<BS>",           nvim_tree_api.node.navigate.parent_close,     opts("Close Directory"))
-- set("n", "<CR>",           nvim_tree_api.node.open.edit,                 opts("Open"))
-- set("n", "<Tab>",          nvim_tree_api.node.open.preview,              opts("Open Preview"))
-- set("n", ">",              nvim_tree_api.node.navigate.sibling.next,     opts("Next Sibling"))
-- set("n", "<",              nvim_tree_api.node.navigate.sibling.prev,     opts("Previous Sibling"))
-- set("n", ".",              nvim_tree_api.node.run.cmd,                   opts("Run Command"))
-- set("n", "-",              nvim_tree_api.tree.change_root_to_parent,     opts("Up"))
-- set("n", "a",              nvim_tree_api.fs.create,                      opts("Create File Or Directory"))
-- set("n", "bd",             nvim_tree_api.marks.bulk.delete,              opts("Delete Bookmarked"))
-- set("n", "bt",             nvim_tree_api.marks.bulk.trash,               opts("Trash Bookmarked"))
-- set("n", "bmv",            nvim_tree_api.marks.bulk.move,                opts("Move Bookmarked"))
-- set("n", "B",              nvim_tree_api.tree.toggle_no_buffer_filter,   opts("Toggle Filter: No Buffer"))
-- set("n", "c",              nvim_tree_api.fs.copy.node,                   opts("Copy"))
-- set("n", "C",              nvim_tree_api.tree.toggle_git_clean_filter,   opts("Toggle Filter: Git Clean"))
-- set("n", "[c",             nvim_tree_api.node.navigate.git.prev,         opts("Prev Git"))
-- set("n", "]c",             nvim_tree_api.node.navigate.git.next,         opts("Next Git"))
-- set("n", "d",              nvim_tree_api.fs.remove,                      opts("Delete"))
-- set("n", "D",              nvim_tree_api.fs.trash,                       opts("Trash"))
-- set("n", "E",              nvim_tree_api.tree.expand_all,                opts("Expand All"))
-- set("n", "e",              nvim_tree_api.fs.rename_basename,             opts("Rename: Basename"))
-- set("n", "]e",             nvim_tree_api.node.navigate.diagnostics.next, opts("Next Diagnostic"))
-- set("n", "[e",             nvim_tree_api.node.navigate.diagnostics.prev, opts("Prev Diagnostic"))
-- set("n", "F",              nvim_tree_api.live_filter.clear,              opts("Live Filter: Clear"))
-- set("n", "f",              nvim_tree_api.live_filter.start,              opts("Live Filter: Start"))
-- set("n", "g?",             nvim_tree_api.tree.toggle_help,               opts("Help"))
-- set("n", "gy",             nvim_tree_api.fs.copy.absolute_path,          opts("Copy Absolute Path"))
-- set("n", "ge",             nvim_tree_api.fs.copy.basename,               opts("Copy Basename"))
-- set("n", "H",              nvim_tree_api.tree.toggle_hidden_filter,      opts("Toggle Filter: Dotfiles"))
-- set("n", "I",              nvim_tree_api.tree.toggle_gitignore_filter,   opts("Toggle Filter: Git Ignore"))
-- set("n", "J",              nvim_tree_api.node.navigate.sibling.last,     opts("Last Sibling"))
-- set("n", "K",              nvim_tree_api.node.navigate.sibling.first,    opts("First Sibling"))
-- set("n", "L",              nvim_tree_api.node.open.toggle_group_empty,   opts("Toggle Group Empty"))
-- set("n", "M",              nvim_tree_api.tree.toggle_no_bookmark_filter, opts("Toggle Filter: No Bookmark"))
-- set("n", "m",              nvim_tree_api.marks.toggle,                   opts("Toggle Bookmark"))
-- set("n", "o",              nvim_tree_api.node.open.edit,                 opts("Open"))
-- set("n", "O",              nvim_tree_api.node.open.no_window_picker,     opts("Open: No Window Picker"))
-- set("n", "p",              nvim_tree_api.fs.paste,                       opts("Paste"))
-- set("n", "P",              nvim_tree_api.node.navigate.parent,           opts("Parent Directory"))
-- set("n", "q",              nvim_tree_api.tree.close,                     opts("Close"))
-- set("n", "r",              nvim_tree_api.fs.rename,                      opts("Rename"))
-- set("n", "R",              nvim_tree_api.tree.reload,                    opts("Refresh"))
-- set("n", "s",              nvim_tree_api.node.run.system,                opts("Run System"))
-- set("n", "S",              nvim_tree_api.tree.search_node,               opts("Search"))
-- set("n", "u",              nvim_tree_api.fs.rename_full,                 opts("Rename: Full Path"))
-- set("n", "U",              nvim_tree_api.tree.toggle_custom_filter,      opts("Toggle Filter: Hidden"))
-- set("n", "W",              nvim_tree_api.tree.collapse_all,              opts("Collapse"))
-- set("n", "x",              nvim_tree_api.fs.cut,                         opts("Cut"))
-- set("n", "y",              nvim_tree_api.fs.copy.filename,               opts("Copy Name"))
-- set("n", "Y",              nvim_tree_api.fs.copy.relative_path,          opts("Copy Relative Path"))
-- set("n", "<2-LeftMouse>",  nvim_tree_api.node.open.edit,                 opts("Open"))
-- set("n", "<2-RightMouse>", nvim_tree_api.tree.change_root_to_node,       opts("CD"))
