# Ori
# preload = ~/Pictures/Wallpapers/wallpaperflare.com_wallpaper.jpg
# wallpaper = eDP-1,~/Pictures/Wallpapers/wallpaperflare.com_wallpaper.jpg

preload = ~/Pictures/Wallpapers/Stars.jpg
wallpaper = eDP-1,~/Pictures/Wallpapers/Stars.jpg
splash = true

#fully disable ipc
ipc = off
