source = ~/.config/hypr/apps.conf

exec-once = uwsm app -- hyprswitch init --show-title --size-factor 5.5 --workspaces-per-row 5
exec-once = uwsm app -- hyprpaper
exec-once = uwsm app -- hyprpanel
# exec-once = ~/StartWallpaper.sh
# exec-once = hyprlux

exec-once = uwsm app -- blueman-applet
exec-once = uwsm app -- sway-audio-idle-inhibit
exec-once = uwsm app -- udiskie
exec-once = uwsm app -- albert

exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = xhost +si:localuser:$USER

exec-once = [workspace 1 silent] uwsm app -- $browser
exec-once = [workspace 2 silent] uwsm app -- telegram-desktop
exec-once = [workspace 10 silent] uwsm app -- spotify
exec-once = [workspace 11 silent] uwsm app -- nekobox
