If:
  PathMatch: ".*.(cpp|hpp)$"
CompileFlags:
  Add:
    - "-Wall"
    - "-Wextra"
    - "-Weffc++"
    - "-Wcast-align"
    - "-Wcast-qual"
    - "-Wchar-subscripts"
    - "-Wconditionally-supported"
    - "-Wconversion"
    - "-Wctor-dtor-privacy"
    - "-Wfloat-equal"
    - "-Wformat-nonliteral"
    - "-Wformat-security"
    - "-Wformat-signedness"
    - "-Wformat=2"
    - "-Winline"
    - "-Wlogical-op"
    - "-Woverloaded-virtual"
    - "-Wpacked"
    - "-Wpointer-arith"
    - "-Winit-self"
    - "-Wredundant-decls"
    - "-Wshadow"
    - "-Wno-sign-conversion"
    - "-Wsign-conversion"
    - "-Wsign-promo"
    - "-Wstrict-null-sentinel"
    - "-Wstrict-overflow=2"
    - "-Wsuggest-attribute=noreturn"
    - "-Wsuggest-final-methods"
    - "-Wsuggest-final-types"
    - "-Wsuggest-override"
    - "-Wswitch-default"
    - "-Wswitch-enum"
    - "-Wsync-nand"
    - "-Wundef"
    - "-Wunreachable-code"
    - "-Wunused"
    - "-Wuseless-cast"
    - "-Wvariadic-macros"
    - "-Wstack-protector"
  Remove:
    - "-fdeps-format*"
    - "-fmodule*"
