---
If:
  PathMatch: .*\.c$
CompileFlags:
  Remove:
    - -std=*
  Add:
    - -std=gnu23
    - -Wall
    - -Wextra
    - -Wshadow
---
If:
  PathMatch: .*\.(cc|cpp|cxx|c\+\+|hh|hpp|hxx|h\+\+)$
CompileFlags:
  Remove:
    - -std=*
  Add:
    - -std=gnu++23
    - -Wall
    - -Wextra
    - -Wshadow
    - -Weffc++

