# Noctalia theme for snappy-switcher

[colors]
background = #1a1a1aaa
card_bg = #080808aa
card_selected =  #1c1c1cff
text_color = #f3d8d8dd
subtext_color =  #f3d8d8cc
border_color =  #70635aff
bundle_bg = #934900ff
badge_bg =  #ffa247aa
badge_text_color = #1a1a1aaa
badge_bg_selected = #ffa247cc
badge_text_color_selected = #1a1a1aff